package com.graybar.dd.adwords.prod;

import com.google.api.ads.adwords.lib.jaxb.v201607.DateRange;
import com.google.api.ads.adwords.lib.jaxb.v201607.Selector;
import com.google.common.collect.Lists;

@SuppressWarnings("unused")
public class ReportBuilder {
	
	public static Selector ReportBuilder (String reportName, String dateMin, String dateMax) {
		Selector selector = new Selector();
//		Lines 15-18 should be commented out if using a relative DateRangeType, such 
//		as LAST_MONTH or THIS_YEAR. Uncomment to use a CUSTOM_DATE.

//		DateRange dateRange = new DateRange();
//		dateRange.setMin(dateMin);
//		dateRange.setMax(dateMax);
//		selector.setDateRange(dateRange);
		if (reportName == "ACCOUNT_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
					"AccountDescriptiveName",
					"ActiveViewCpm",
					"ActiveViewCtr",
					"ActiveViewImpressions",
					"ActiveViewMeasurability",
					"ActiveViewMeasurableCost",
					"ActiveViewMeasurableImpressions",
					"ActiveViewViewability",
					"AdNetworkType1",
					"AdNetworkType2",
					"AllConversionRate",
					"AllConversions",
					"AllConversionValue",
					"AverageCost",
					"AverageCpc",
					"AverageCpe",
					"AverageCpm",
					"AverageCpv",
					"AveragePosition",
					"CanManageClients",
					"Clicks",
					//"ClickType",
					//"ContentBudgetLostImpressionShare",
					//"ContentImpressionShare",
					//"ContentRankLostImpressionShare",
					//"ConversionCategoryName",
					"ConversionRate",
					"Conversions",
					//"ConversionTrackerId",
					//"ConversionTypeName",
					"ConversionValue",
					"Cost",
					"CostPerAllConversion",
					"CostPerConversion",
					"CrossDeviceConversions",
					"Ctr",
					"CustomerDescriptiveName",
					"Date",
					"Device",
					"EngagementRate",
					"Engagements",
					"ExternalCustomerId",
					//"HourOfDay",
					"Impressions",
					"InteractionRate",
					"Interactions",
					"InteractionTypes",
					"InvalidClickRate",
					"InvalidClicks",
					"IsAutoTaggingEnabled",
					"IsTestAccount",
					"PrimaryCompanyName",
					//"SearchBudgetLostImpressionShare",
					//"SearchExactMatchImpressionShare",
					//"SearchImpressionShare",
					//"SearchRankLostImpressionShare",
					//"Slot",
					"ValuePerAllConversion",
					"ValuePerConversion",
					"VideoViewRate",
					"VideoViews",
					"ViewThroughConversions"
					));				
		}
		if (reportName == "ADGROUP_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdGroupDesktopBidModifier",
                    "AdGroupId",
                    "AdGroupMobileBidModifier",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdGroupTabletBidModifier",
                    "AdNetworkType1",
                    "AdNetworkType2",
//                     "AdvertiserExperimentSegmentationBin",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
//                     "AveragePageviews",
                    "AveragePosition",
//                     "AverageTimeOnSite",
                    "BaseAdGroupId",
                    "BaseCampaignId",
                    "BiddingStrategyId",
                    "BiddingStrategyName",
                    "BiddingStrategySource",
                    "BiddingStrategyType",
                    "BidType",
                    "BounceRate",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "ClickAssistedConversions",
                    "ClickAssistedConversionsOverLastClickConversions",
                    "ClickAssistedConversionValue",
                    "Clicks",
//                     "ClickSignificance",
//                     "ClickType",
                    "ContentBidCriterionTypeGroup",
                    "ContentImpressionShare",
                    "ContentRankLostImpressionShare",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
//                     "CostSignificance",
                    "CpcBid",
//                     "CpcSignificance",
                    "CpmBid",
//                     "CpmSignificance",
                    "CpvBid",
                    "CrossDeviceConversions",
                    "Ctr",
//                     "CtrSignificance",
                    "CustomerDescriptiveName",
                    "Date",
//                     "Device",
                    "EngagementRate",
                    "Engagements",
                    "EnhancedCpcEnabled",
                    "EnhancedCpvEnabled",
                    "ExternalCustomerId",
                    "GmailForwards",
                    "GmailSaves",
                    "GmailSecondaryClicks",
//                     "HourOfDay",
                    "ImpressionAssistedConversions",
                    "ImpressionAssistedConversionsOverLastClickConversions",
                    "ImpressionAssistedConversionValue",
                    "Impressions",
//                     "ImpressionSignificance",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "LabelIds",
                    "Labels",
                    "NumOfflineImpressions",
                    "NumOfflineInteractions",
                    "OfflineInteractionRate",
                    "PercentNewVisitors",
//                     "PositionSignificance",
                    "PrimaryCompanyName",
                    "RelativeCtr",
                    "SearchExactMatchImpressionShare",
                    "SearchImpressionShare",
                    "SearchRankLostImpressionShare",
//                     "Slot",
                    "TargetCpa",
                    "TargetCpaBidSource",
                    "TrackingUrlTemplate",
                    "UrlCustomParameters",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
//                     "ViewThroughConversionsSignificance"
                    ));
		}
		if (reportName == "AD_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
					"AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdGroupAdDisapprovalReasons",
                    "AdGroupAdTrademarkDisapproved",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AdType",
//                     "AdvertiserExperimentSegmentationBin",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePageviews",
                    "AveragePosition",
                    "AverageTimeOnSite",
                    "BaseAdGroupId",
                    "BaseCampaignId",
                    "BounceRate",
                    "BusinessName",
                    "CallOnlyPhoneNumber",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "ClickAssistedConversions",
                    "ClickAssistedConversionsOverLastClickConversions",
                    "ClickAssistedConversionValue",
                    "Clicks",
//                     "ClickSignificance",
//                     "ClickType",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
//                     "CostSignificance",
//                     "CpcSignificance",
//                     "CpmSignificance",
                    "CreativeApprovalStatus",
                    "CreativeDestinationUrl",
                    "CreativeFinalAppUrls",
                    "CreativeFinalMobileUrls",
                    "CreativeFinalUrls",
                    "CreativeTrackingUrlTemplate",
                    "CreativeUrlCustomParameters",
                    "CriterionId",
                    "CriterionType",
                    "CrossDeviceConversions",
                    "Ctr",
//                     "CtrSignificance",
                    "CustomerDescriptiveName",
                    "Date",
                    "Description",
                    "Description1",
                    "Description2",
//                     "Device",
                    "DevicePreference",
                    "DisplayUrl",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "GmailForwards",
                    "GmailSaves",
                    "GmailSecondaryClicks",
                    "Headline",
                    "HeadlinePart1",
                    "HeadlinePart2",
                    "Id",
                    "ImageAdUrl",
                    "ImageCreativeImageHeight",
                    "ImageCreativeImageWidth",
                    "ImageCreativeName",
                    "ImpressionAssistedConversions",
                    "ImpressionAssistedConversionsOverLastClickConversions",
                    "ImpressionAssistedConversionValue",
                    "Impressions",
//                     "ImpressionSignificance",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsNegative",
                    "LabelIds",
                    "Labels",
                    "LongHeadline",
                    "Path1",
                    "Path2",
                    "PercentNewVisitors",
//                     "PositionSignificance",
                    "PrimaryCompanyName",
                     "ShortHeadline",
//                     "Slot",
                    "Status",
                    "Trademarks",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
//                     "ViewThroughConversionsSignificance",
                    ));
		}
		if (reportName == "AUDIENCE_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePosition",
                    "BaseAdGroupId",
                    "BaseCampaignId",
                    "BidModifier",
                    "BidType",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ClickType",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CpcBid",
                    "CpcBidSource",
                    "CpmBid",
                    "CpmBidSource",
                    "Criteria",
                    "CriteriaDestinationUrl",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Device",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "FinalAppUrls",
                    "FinalMobileUrls",
                    "FinalUrls",
                    "GmailForwards",
                    "GmailSaves",
                    "GmailSecondaryClicks",
                    "Id",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsNegative",
                    "IsRestrict",
                    "PrimaryCompanyName",
//                     "Slot",
                    "Status",
                    "TrackingUrlTemplate",
                    "UrlCustomParameters",
                    "UserListName",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdFormat",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CriteriaParameters",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "DisplayName",
                    "Domain",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsAutoOptimized",
                    "IsBidOnPath",
                    "IsPathExcluded",
                    "PrimaryCompanyName",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "CAMPAIGN_LOCATION_TARGET_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePosition",
                    "BidModifier",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
                    "ConversionRate",
                    "Conversions",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "Id",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsNegative",
                    "PrimaryCompanyName",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "CAMPAIGN_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdNetworkType1",
                    "AdNetworkType2",
//                     "AdvertiserExperimentSegmentationBin",
                    "AdvertisingChannelSubType",
                    "AdvertisingChannelType",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "Amount",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
//                     "AverageFrequency",
//                     "AveragePageviews",
                    "AveragePosition",
//                     "AverageTimeOnSite",
                    "BaseCampaignId",
                    "BiddingStrategyId",
                    "BiddingStrategyName",
                    "BiddingStrategyType",
                    "BidType",
                    "BounceRate",
                    "BudgetId",
                    "CampaignDesktopBidModifier",
                    "CampaignId",
                    "CampaignMobileBidModifier",
                    "CampaignName",
                    "CampaignStatus",
                    "CampaignTabletBidModifier",
                    "CampaignTrialType",
                    "ClickAssistedConversions",
                    "ClickAssistedConversionsOverLastClickConversions",
                    "ClickAssistedConversionValue",
                    "Clicks",
//                     "ClickSignificance",
//                     "ClickType",
                    "ContentBudgetLostImpressionShare",
                    "ContentImpressionShare",
                    "ContentRankLostImpressionShare",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
//                     "CostSignificance",
//                     "CpcSignificance",
//                     "CpmSignificance",
                    "CrossDeviceConversions",
                    "Ctr",
//                     "CtrSignificance",
                    "CustomerDescriptiveName",
                    "Date",
//                     "Device",
                    "EndDate",
                    "EngagementRate",
                    "Engagements",
                    "EnhancedCpcEnabled",
                    "EnhancedCpvEnabled",
                    "ExternalCustomerId",
                    "GmailForwards",
                    "GmailSaves",
                    "GmailSecondaryClicks",
//                     "HourOfDay",
                    "ImpressionAssistedConversions",
                    "ImpressionAssistedConversionsOverLastClickConversions",
                    "ImpressionAssistedConversionValue",
//                     "ImpressionReach",
                    "Impressions",
//                     "ImpressionSignificance",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "InvalidClickRate",
                    "InvalidClicks",
                    "IsBudgetExplicitlyShared",
                    "LabelIds",
                    "Labels",
                    "NumOfflineImpressions",
                    "NumOfflineInteractions",
                    "OfflineInteractionRate",
                    "PercentNewVisitors",
                    "Period",
//                     "PositionSignificance",
                    "PrimaryCompanyName",
                    "RelativeCtr",
                    "SearchBudgetLostImpressionShare",
                    "SearchExactMatchImpressionShare",
                    "SearchImpressionShare",
                    "SearchRankLostImpressionShare",
                    "ServingStatus",
//                     "Slot",
                    "StartDate",
                    "TrackingUrlTemplate",
                    "UrlCustomParameters",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
//                     "ViewThroughConversionsSignificance
                    ));
		}
		if (reportName == "CLICK_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdFormat",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AoiMostSpecificTargetId",
                    "CampaignId",
                    "CampaignLocationTargetId",
                    "CampaignName",
                    "CampaignStatus",
                    "ClickType",
                    "CreativeId",
                    "CriteriaId",
                    "CriteriaParameters",
                    "Date",
                    "Device",
                    "ExternalCustomerId",
                    "GclId",
                    "KeywordMatchType",
                    "LopMostSpecificTargetId",
                    "Page",
                    "Slot",
                    "UserListId"
                    ));
		}
		if (reportName == "FINAL_URL_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AdvertisingChannelType",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePosition",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ClickType",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CriteriaParameters",
                    "CriteriaTypeName",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Device",
                    "EffectiveFinalUrl",
                    "EffectiveTrackingUrlTemplate",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "PrimaryCompanyName",
//                     "Slot",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoViewRate",
                    "VideoViews"
                    ));
		}
		if (reportName == "GEO_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdFormat",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePosition",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "CityCriteriaId",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CountryCriteriaId",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Device",
                    "ExternalCustomerId",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsTargetingLocation",
                    "LocationType",
                    "MetroCriteriaId",
					"MostSpecificCriteriaId",
                    "PrimaryCompanyName",
                    "RegionCriteriaId",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "KEYWORDLESS_CATEGORY_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCpc",
                    "AverageCpm",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Category0",
                    "Category1",
                    "Category2",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CriterionId",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Domain",
                    "ExternalCustomerId",
                    "Impressions",
                    "PrimaryCompanyName",
                    "ValuePerAllConversion",
                    "ValuePerConversion"
                    ));
		}
		if (reportName == "KEYWORDLESS_QUERY_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCpc",
                    "AverageCpm",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "CategoryPaths",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CriterionId",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Domain",
                    "ExternalCustomerId",
                    "Impressions",
                    "Line1",
                    "PrimaryCompanyName",
                    "Query",
                    "Title",
                    "Url",
                    "ValuePerAllConversion",
                    "ValuePerConversion"
                    ));
		}
		if (reportName == "KEYWORDS_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
//                     "AdvertiserExperimentSegmentationBin",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "ApprovalStatus",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePageviews",
                    "AveragePosition",
                    "AverageTimeOnSite",
                    "BaseAdGroupId",
                    "BaseCampaignId",
                    "BiddingStrategyId",
                    "BiddingStrategyName",
                    "BiddingStrategySource",
                    "BiddingStrategyType",
                    "BidType",
                    "BounceRate",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "ClickAssistedConversions",
                    "ClickAssistedConversionsOverLastClickConversions",
                    "ClickAssistedConversionValue",
                    "Clicks",
//                     "ClickSignificance",
//                     "ClickType",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
//                     "CostSignificance",
                    "CpcBid",
                    "CpcBidSource",
//                     "CpcSignificance",
                    "CpmBid",
//                     "CpmSignificance",
                    "CreativeQualityScore",
                    "Criteria",
                    "CriteriaDestinationUrl",
                    "CrossDeviceConversions",
                    "Ctr",
//                     "CtrSignificance",
                    "CustomerDescriptiveName",
                    "Date",
//                     "Device",
                    "EngagementRate",
                    "Engagements",
                    "EnhancedCpcEnabled",
                    "EstimatedAddClicksAtFirstPositionCpc",
                    "EstimatedAddCostAtFirstPositionCpc",
                    "ExternalCustomerId",
                    "FinalAppUrls",
                    "FinalMobileUrls",
                    "FinalUrls",
                    "FirstPageCpc",
                    "FirstPositionCpc",
                    "GmailForwards",
                    "GmailSaves",
                    "GmailSecondaryClicks",
                    "HasQualityScore",
                    "Id",
                    "ImpressionAssistedConversions",
                    "ImpressionAssistedConversionsOverLastClickConversions",
                    "ImpressionAssistedConversionValue",
                    "Impressions",
//                     "ImpressionSignificance",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsNegative",
                    "KeywordMatchType",
                    "LabelIds",
                    "Labels",
                    "PercentNewVisitors",
//                     "PositionSignificance",
                    "PostClickQualityScore",
                    "PrimaryCompanyName",
                    "QualityScore",
                    "SearchExactMatchImpressionShare",
                    "SearchImpressionShare",
                    "SearchPredictedCtr",
                    "SearchRankLostImpressionShare",
//                     "Slot",
                    "Status",
                    "SystemServingStatus",
                    "TopOfPageCpc",
                    "TrackingUrlTemplate",
                    "UrlCustomParameters",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
//                     "ViewThroughConversionsSignificance",
                    ));
		}
		if (reportName == "PAID_ORGANIC_QUERY_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AverageCpc",
                    "AveragePosition",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
                    "CombinedAdsOrganicClicks",
                    "CombinedAdsOrganicClicksPerQuery",
                    "CombinedAdsOrganicQueries",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "ExternalCustomerId",
                    "Impressions",
                    "KeywordId",
                    "KeywordTextMatchingQuery",
                    "OrganicAveragePosition",
                    "OrganicClicks",
                    "OrganicClicksPerQuery",
                    "OrganicImpressions",
                    "OrganicImpressionsPerQuery",
                    "OrganicQueries",
                    "PrimaryCompanyName",
                    "QueryMatchType",
                    "SearchQuery",
                    "SerpType"
                    ));
		}
		if (reportName == "PLACEMENT_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "BaseAdGroupId",
                    "BaseCampaignId",
                    "BidModifier",
                    "BidType",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ClickType",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CpcBid",
                    "CpcBidSource",
                    "CpmBid",
                    "CpmBidSource",
                    "Criteria",
                    "CriteriaDestinationUrl",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Device",
                    "DisplayName",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "FinalAppUrls",
                    "FinalMobileUrls",
                    "FinalUrls",
                    "GmailForwards",
                    "GmailSaves",
                    "GmailSecondaryClicks",
                    "Id",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsNegative",
                    "IsRestrict",
                    "PrimaryCompanyName",
                    "Status",
                    "TrackingUrlTemplate",
                    "UrlCustomParameters",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "PRODUCT_PARTITION_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCpc",
                    "AverageCpm",
                    "BenchmarkAverageMaxCpc",
                    "BenchmarkCtr",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ClickType",
                    "ConversionRate",
                    "Conversions",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CpcBid",
                    "CriteriaDestinationUrl",
                    "CrossDeviceConversions",
                    "Ctr",
                    "Date",
//                     "Device",
                    "ExternalCustomerId",
                    "Id",
                    "Impressions",
                    "IsNegative",
                    "ParentCriterionId",
                    "PartitionType",
                    "ProductGroup",
                    "SearchClickShare",
                    "SearchImpressionShare",
                    "TrackingUrlTemplate",
                    "UrlCustomParameters",
                    "ValuePerAllConversion",
                    "ValuePerConversion"
                    ));
		}
		if (reportName == "SEARCH_QUERY_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdFormat",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "AveragePosition",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CreativeId",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "DestinationUrl",
                    "Device",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "FinalUrl",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "KeywordId",
                    "KeywordTextMatchingQuery",
                    "PrimaryCompanyName",
                    "Query",
                    "QueryMatchTypeWithVariant",
                    "TrackingUrlTemplate",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "SHARED_SET_CRITERIA_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
					"AccountDescriptiveName",
					"Criteria",
					"ExternalCustomerId",
					"Id",
					"KeywordMatchType",
					"SharedSetId"
					));
		}
		if (reportName == "SHARED_SET_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ExternalCustomerId",
                    "MemberCount",
                    "Name",
                    "ReferenceCount",
                    "SharedSetId",
                    "Status",
                    "Type"
                    ));
		}
		if (reportName == "SHOPPING_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AggregatorId",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCpc",
                    "Brand",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "CategoryL1",
                    "CategoryL2",
                    "CategoryL3",
                    "CategoryL4",
                    "CategoryL5",
                    "Channel",
                    "ChannelExclusivity",
                    "Clicks",
//                     "ClickType",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CountryCriteriaId",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomAttribute0",
                    "CustomAttribute1",
                    "CustomAttribute2",
                    "CustomAttribute3",
                    "CustomAttribute4",
                    "Date",
                    "Device",
                    "ExternalCustomerId",
                    "Impressions",
                    "LanguageCriteriaId",
                    "MerchantId",
                    "OfferId",
                    "ProductCondition",
                    "ProductTypeL1",
                    "ProductTypeL2",
                    "ProductTypeL3",
                    "ProductTypeL4",
                    "ProductTypeL5",
                    "SearchClickShare",
                    "SearchImpressionShare",
//                     "StoreId",
                    "ValuePerAllConversion",
                    "ValuePerConversion"
                    ));
		}
		if (reportName == "URL_PERFORMANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "ActiveViewCpm",
                    "ActiveViewCtr",
                    "ActiveViewImpressions",
                    "ActiveViewMeasurability",
                    "ActiveViewMeasurableCost",
                    "ActiveViewMeasurableImpressions",
                    "ActiveViewViewability",
                    "AdFormat",
                    "AdGroupCriterionStatus",
                    "AdGroupId",
                    "AdGroupName",
                    "AdGroupStatus",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCost",
                    "AverageCpc",
                    "AverageCpe",
                    "AverageCpm",
                    "AverageCpv",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTrackerId",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CriteriaParameters",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "DisplayName",
                    "Domain",
                    "EngagementRate",
                    "Engagements",
                    "ExternalCustomerId",
                    "Impressions",
                    "InteractionRate",
                    "Interactions",
                    "InteractionTypes",
                    "IsAutoOptimized",
                    "IsBidOnPath",
                    "IsPathExcluded",
                    "PrimaryCompanyName",
                    "Url",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "VideoQuartile100Rate",
                    "VideoQuartile25Rate",
                    "VideoQuartile50Rate",
                    "VideoQuartile75Rate",
                    "VideoViewRate",
                    "VideoViews",
                    "ViewThroughConversions"
                    ));
		}
		if (reportName == "USER_AD_DISTANCE_REPORT") {
			selector.getFields().addAll(Lists.newArrayList(
                    "AccountDescriptiveName",
                    "AdNetworkType1",
                    "AdNetworkType2",
                    "AllConversionRate",
                    "AllConversions",
                    "AllConversionValue",
                    "AverageCpc",
                    "AverageCpm",
                    "AveragePosition",
                    "CampaignId",
                    "CampaignName",
                    "CampaignStatus",
                    "Clicks",
//                     "ConversionCategoryName",
                    "ConversionRate",
                    "Conversions",
//                     "ConversionTypeName",
                    "ConversionValue",
                    "Cost",
                    "CostPerAllConversion",
                    "CostPerConversion",
                    "CrossDeviceConversions",
                    "Ctr",
                    "CustomerDescriptiveName",
                    "Date",
                    "Device",
                    "DistanceBucket",
                    "ExternalCustomerId",
                    "Impressions",
                    "PrimaryCompanyName",
                    "ValuePerAllConversion",
                    "ValuePerConversion",
                    "ViewThroughConversions"
                    ));
		}
		return selector;
	}


}
